title: DJ Boots Productions
company: DJ Boots Productions
favicon: assets/images/favicon.ico
type: website
description: Lorem Ipsum
keywords: 
  - DJ Boots Productions
  - Event Planning
image: /assets/images/site-preview.png
url: https://djbootsprod.netlify.com/
email: bryanmaldo7@gmail.com
twitterUrl: http://www.twitter.com/
facebookUrl: https://www.facebook.com/bryan.maldonado.9634340
googleAnalyticsId: ""
markdown: kramdown
source: src/jekyll
destination: dist
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - package-lock.json
  - src/vendors