title: DJ Boots Productions
company: DJ Boots Productions
favicon: assets/images/favicon.ico
type: website
description: Lorem Ipsum
keywords: 
  - DJ Boots Productions
  - Event Planning
  - Parties
  - Weddings
developer: Brightside Tech
developerUrl: '#'
image: /assets/images/site-preview.png
url: https://djbootsprod.netlify.com/
email: bryanmaldo7@gmail.com
phone: (760)-844-0749
instagramUrl: https://www.instagram.com/djbootspro/
facebookUrl: https://www.facebook.com/bryan.maldonado.9634340
googleAnalyticsId: ""
markdown: kramdown
source: src/jekyll
destination: dist
include:
  - _pages
plugins:
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - package-lock.json
  - src/vendors