[build]
    publish = "_site"
    command = "npm run build"
[context.development]
    publish = "_site"
    command = "npm run build:dev"
[context.test]
    publish = "_site"
    command = "npm run build:test"
[[redirects]]
    from = "https://djbootsprod.netlify.com/*"
    to = "https://djbootsprod.com/:splat"
    status = 301